name: scp maps
on: 
  push:
    branches:
      - master
jobs:
  DeployMaps:
    name: Map Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HIGHORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "voting.json"
        target: "~/containers/eldewrito/cache/"
        overwrite: 1
        
  DeployVoteConfig:
    name: Vote Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HIGHORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "voting.json"
        target: "~/containers/eldewrito/cache/"
        overwrite: 1
        
  CopyLocal:
    needs: [DeployMaps, DeployVoteConfig]
    name: Copy Local Files
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HIGHORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: echo ${{ secrets.PASSWORD }} | sudo -S ~/containers/eldewrito/cache/copy.sh
